site_name: My Docs
site_url: http://localhost
theme:
  name: material
  features:
    - navigation.indexes
  palette:
    primary: deep orange
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono
plugins:
  - search
  # - blog:
  #     blog_toc: true
  #     archive_date_format: MMMM yyyy
  #     categories_allowed:
  #       - Holidays
  #       - News
  #     pagination_per_page: 5
  # - social
      
nav:
  - Home: index.md
  - Blog:
     - blog/index.md
     - Tags: blog/tags.md